### ISSUE TITLE
Build fails on macOS 12.6 due to redefinition of std::hash and std::less

### ISSUE THREAD

**Issue by smarsching** [ChimeraTK/DeviceAccess#281]
The build on macOS 12.6 fails:

```
[  1%] Building CXX object CMakeFiles/ChimeraTK-DeviceAccess.dir/device/src/DataConsistencyGroup.cc.o
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/src/DataConsistencyGroup.cc:4:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/DataConsistencyGroup.h:5:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementAbstractor.h:5:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device_backends/include/TransferElement.h:8:
/Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementID.h:58:24: error: 
      reference to 'hash' is ambiguous
    friend struct std::hash<TransferElementID>;
                       ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/typeindex:89:50: note: 
      candidate found by name lookup is 'std::__1::hash'
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS hash;
                                                 ^
/Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementID.h:10:10: note: 
      candidate found by name lookup is 'std::hash'
  struct hash;
         ^
/Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementID.h:61:24: error: 
      reference to 'less' is ambiguous
    friend struct std::less<TransferElementID>;
                       ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__functional_base:50:29: note: 
      candidate found by name lookup is 'std::__1::less'
struct _LIBCPP_TEMPLATE_VIS less : binary_function<_Tp, _Tp, bool>
                            ^
/Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementID.h:13:10: note: 
      candidate found by name lookup is 'std::less'
  struct less;
         ^
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/src/DataConsistencyGroup.cc:4:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/DataConsistencyGroup.h:5:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementAbstractor.h:5:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device_backends/include/TransferElement.h:17:
In file included from /usr/local/include/boost/thread.hpp:13:
In file included from /usr/local/include/boost/thread/thread.hpp:12:
In file included from /usr/local/include/boost/thread/thread_only.hpp:17:
In file included from /usr/local/include/boost/thread/pthread/thread_data.hpp:10:
In file included from /usr/local/include/boost/thread/exceptions.hpp:22:
In file included from /usr/local/include/boost/system/system_error.hpp:9:
In file included from /usr/local/include/boost/system/errc.hpp:14:
In file included from /usr/local/include/boost/system/detail/error_code.hpp:14:
/usr/local/include/boost/system/detail/error_category.hpp:170:21: error: 
      reference to 'less' is ambiguous
        return std::less<error_category const *>()( &lhs, &rhs );
                    ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__functional_base:50:29: note: 
      candidate found by name lookup is 'std::__1::less'
struct _LIBCPP_TEMPLATE_VIS less : binary_function<_Tp, _Tp, bool>
                            ^
/Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementID.h:13:10: note: 
      candidate found by name lookup is 'std::less'
  struct less;
         ^
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/src/DataConsistencyGroup.cc:4:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/DataConsistencyGroup.h:5:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementAbstractor.h:5:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device_backends/include/TransferElement.h:17:
In file included from /usr/local/include/boost/thread.hpp:13:
In file included from /usr/local/include/boost/thread/thread.hpp:12:
In file included from /usr/local/include/boost/thread/thread_only.hpp:17:
In file included from /usr/local/include/boost/thread/pthread/thread_data.hpp:10:
In file included from /usr/local/include/boost/thread/exceptions.hpp:22:
In file included from /usr/local/include/boost/system/system_error.hpp:9:
In file included from /usr/local/include/boost/system/errc.hpp:14:
/usr/local/include/boost/system/detail/error_code.hpp:688:21: error: reference
      to 'hash' is ambiguous
        return std::hash<std::error_code>()( e2 );
                    ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/typeindex:89:50: note: 
      candidate found by name lookup is 'std::__1::hash'
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS hash;
                                                 ^
/Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementID.h:10:10: note: 
      candidate found by name lookup is 'std::hash'
  struct hash;
         ^
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/src/DataConsistencyGroup.cc:4:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/DataConsistencyGroup.h:5:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementAbstractor.h:5:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device_backends/include/TransferElement.h:17:
In file included from /usr/local/include/boost/thread.hpp:24:
In file included from /usr/local/include/boost/thread/future.hpp:51:
In file included from /usr/local/include/boost/optional.hpp:15:
In file included from /usr/local/include/boost/optional/optional.hpp:68:
/usr/local/include/boost/optional/detail/optional_hash.hpp:25:10: error: 
      reference to 'hash' is ambiguous
  struct hash<boost::optional<T> >
         ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/typeindex:89:50: note: 
      candidate found by name lookup is 'std::__1::hash'
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS hash;
                                                 ^
/Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementID.h:10:10: note: 
      candidate found by name lookup is 'std::hash'
  struct hash;
         ^
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/src/DataConsistencyGroup.cc:4:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/DataConsistencyGroup.h:5:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementAbstractor.h:5:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device_backends/include/TransferElement.h:17:
In file included from /usr/local/include/boost/thread.hpp:24:
In file included from /usr/local/include/boost/thread/future.hpp:51:
In file included from /usr/local/include/boost/optional.hpp:15:
In file included from /usr/local/include/boost/optional/optional.hpp:68:
/usr/local/include/boost/optional/detail/optional_hash.hpp:31:25: error: 
      reference to 'hash' is ambiguous
      return arg ? std::hash<T>()(*arg) : result_type();
                        ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/typeindex:89:50: note: 
      candidate found by name lookup is 'std::__1::hash'
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS hash;
                                                 ^
/Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementID.h:10:10: note: 
      candidate found by name lookup is 'std::hash'
  struct hash;
         ^
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/src/DataConsistencyGroup.cc:4:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/DataConsistencyGroup.h:5:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementAbstractor.h:5:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device_backends/include/TransferElement.h:17:
In file included from /usr/local/include/boost/thread.hpp:24:
In file included from /usr/local/include/boost/thread/future.hpp:51:
In file included from /usr/local/include/boost/optional.hpp:15:
In file included from /usr/local/include/boost/optional/optional.hpp:68:
/usr/local/include/boost/optional/detail/optional_hash.hpp:36:10: error: 
      reference to 'hash' is ambiguous
  struct hash<boost::optional<T&> >
         ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/typeindex:89:50: note: 
      candidate found by name lookup is 'std::__1::hash'
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS hash;
                                                 ^
/Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementID.h:10:10: note: 
      candidate found by name lookup is 'std::hash'
  struct hash;
         ^
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/src/DataConsistencyGroup.cc:4:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/DataConsistencyGroup.h:5:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementAbstractor.h:5:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device_backends/include/TransferElement.h:17:
In file included from /usr/local/include/boost/thread.hpp:24:
In file included from /usr/local/include/boost/thread/future.hpp:51:
In file included from /usr/local/include/boost/optional.hpp:15:
In file included from /usr/local/include/boost/optional/optional.hpp:68:
/usr/local/include/boost/optional/detail/optional_hash.hpp:42:25: error: 
      reference to 'hash' is ambiguous
      return arg ? std::hash<T>()(*arg) : result_type();
                        ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/typeindex:89:50: note: 
      candidate found by name lookup is 'std::__1::hash'
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS hash;
                                                 ^
/Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementID.h:10:10: note: 
      candidate found by name lookup is 'std::hash'
  struct hash;
         ^
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/src/DataConsistencyGroup.cc:4:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/DataConsistencyGroup.h:5:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementAbstractor.h:5:
/Users/termi/Documents/ChimeraTK/DeviceAccess/device_backends/include/TransferElement.h:881:10: error: 
      reference to 'hash' is ambiguous
  struct hash<ChimeraTK::TransferElementID> {
         ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/typeindex:89:50: note: 
      candidate found by name lookup is 'std::__1::hash'
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS hash;
                                                 ^
/Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementID.h:10:10: note: 
      candidate found by name lookup is 'std::hash'
  struct hash;
         ^
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/src/DataConsistencyGroup.cc:4:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/DataConsistencyGroup.h:5:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementAbstractor.h:5:
/Users/termi/Documents/ChimeraTK/DeviceAccess/device_backends/include/TransferElement.h:882:87: error: 
      reference to 'hash' is ambiguous
  ...ChimeraTK::TransferElementID& f) const { return std::hash<size_t>{}(f._i...
                                                          ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/typeindex:89:50: note: 
      candidate found by name lookup is 'std::__1::hash'
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS hash;
                                                 ^
/Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementID.h:10:10: note: 
      candidate found by name lookup is 'std::hash'
  struct hash;
         ^
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/src/DataConsistencyGroup.cc:4:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/DataConsistencyGroup.h:5:
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementAbstractor.h:5:
/Users/termi/Documents/ChimeraTK/DeviceAccess/device_backends/include/TransferElement.h:889:10: error: 
      reference to 'less' is ambiguous
  struct less<ChimeraTK::TransferElementID> {
         ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__functional_base:50:29: note: 
      candidate found by name lookup is 'std::__1::less'
struct _LIBCPP_TEMPLATE_VIS less : binary_function<_Tp, _Tp, bool>
                            ^
/Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementID.h:13:10: note: 
      candidate found by name lookup is 'std::less'
  struct less;
         ^
11 errors generated.
make[2]: *** [CMakeFiles/ChimeraTK-DeviceAccess.dir/device/src/DataConsistencyGroup.cc.o] Error 1
make[1]: *** [CMakeFiles/ChimeraTK-DeviceAccess.dir/all] Error 2
make: *** [all] Error 2
❯ make
Consolidate compiler generated dependencies of target ChimeraTK-DeviceAccess
[  1%] Building CXX object CMakeFiles/ChimeraTK-DeviceAccess.dir/device/src/DataConsistencyGroup.cc.o
[  1%] Building CXX object CMakeFiles/ChimeraTK-DeviceAccess.dir/device/src/DataDescriptor.cpp.o
[  2%] Building CXX object CMakeFiles/ChimeraTK-DeviceAccess.dir/device/src/Device.cc.o
[  2%] Building CXX object CMakeFiles/ChimeraTK-DeviceAccess.dir/device/src/ExperimentalFeatures.cc.o
[  3%] Building CXX object CMakeFiles/ChimeraTK-DeviceAccess.dir/device/src/MetadataCatalogue.cc.o
[  3%] Building CXX object CMakeFiles/ChimeraTK-DeviceAccess.dir/device/src/RegisterCatalogue.cc.o
[  4%] Building CXX object CMakeFiles/ChimeraTK-DeviceAccess.dir/device/src/RegisterInfo.cpp.o
[  4%] Building CXX object CMakeFiles/ChimeraTK-DeviceAccess.dir/device/src/TransferElement.cc.o
[  5%] Building CXX object CMakeFiles/ChimeraTK-DeviceAccess.dir/device/src/TransferElementAbstractor.cc.o
[  5%] Building CXX object CMakeFiles/ChimeraTK-DeviceAccess.dir/device/src/TransferElementID.cc.o
In file included from /Users/termi/Documents/ChimeraTK/DeviceAccess/device/src/TransferElementID.cc:4:
/Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementID.h:63:24: error: 
      explicit specialization of non-template struct 'less'
    friend struct std::less<TransferElementID>;
                       ^   ~~~~~~~~~~~~~~~~~~~
/Users/termi/Documents/ChimeraTK/DeviceAccess/device/include/TransferElementID.h:63:24: error: 
      no struct named 'less' in namespace 'std'
    friend struct std::less<TransferElementID>;
                  ~~~~~^
2 errors generated.
make[2]: *** [CMakeFiles/ChimeraTK-DeviceAccess.dir/device/src/TransferElementID.cc.o] Error 1
make[1]: *** [CMakeFiles/ChimeraTK-DeviceAccess.dir/all] Error 2
make: *** [all] Error 2
```

The problem seems to be that `std::hash` and `std::less` are already declared by the standard libary, but they are also declared in `TransferElementID.h`.

These declarations should be removed and `<functional>` should be included instead. The template specializations (which are probably the reason why the declarations were added in the first place) are fine and can stay.

**Comment by smarsching** [comment]
I encountered two more problems when building on macOS.

The first one was an easy fix: There was a test needing the PCIe backend, but this backend is not available on macOS, so I exclude this test from `CMakeLists.txt` when the backend is not available (we already do this for other tests).

The second one is a bit more delicate, so I need some feedback from @mhier and @killenb:

In `NumericAddressedLowLevelTransferElement`, `NumericAddressedBackend::read` is called, but there are two overloaded versions of this function, so the compiler cannot decide on which one is used. The problem is that one of the functions takes `uint64_t, uint64_t, …` and the other (deprecated one) takes `uint8_t, uint32_t, …`, but `NumericAddressedLowLevelTransferElement` calls it with `size_t, size_t, …`, so there is an ambiguity which one should be used. I guess that Clang (in contrast to GCC) does not assume that size_t == uint64_t when resolving function overloads.

The easiest way to fix this is changing the type of the `_bar` and `_startAdress` member variables in `NumericAddressedLowLevelTransferElement` from `size_t` to `uint64_t`. As a consequence of this, a similar change has to be made in `tests/executables_src/testNumericAddressedBackendRegisterAccessor.cpp`.

I implemented this fix in 116fa9ee0ce40ebe19cd6591af2b6d715f94a6e8. My question is: Is this fix okay, or do you think that it might have unintended effects (e.g. when compiling on 32-bit platforms)?

The alternative would be adding explicit casts from `size_t` to `uint64_t` everywhere where `read` is called, but from my point of view this is not better and makes the code less readable.

If you are fine with the three changes from the `issue-281` branch, I will merge them into the `master` branch.
